language: rust
 - stable
  - beta
  - nightly
script:
  - cargo build --verbose --workspace
  - cargo test --verbose --workspace
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
os:
 - osx
 - linux
 - windows
